use_half: False
use_ddp: Flase

vae_pth: ./weight/VQ-VAE_chn_best.pth # path/to/save/pre-trained model
sim_path: ./weight/all_char_similarity_unicode.json # path/to/save/content_similarity
work_dir: ./z_using_files/lmdb_path/ # workspace
data_path: ./z_using_files/lmdb_path/lmdb/  # path/to/saved/lmdb
data_meta: ./z_using_files/lmdb_path/meta/train.json  # meta/train.json
all_content_json: ./meta/trian_val_all_characters.json
content_font: "LXGWWenKaiGB-Light" # content font

num_embeddings: 100
vae_batch_size: 256
vae_lr: 1e-3
vae_iter: 10000

input_size: 128
num_heads: 8
kshot: 3
num_positive_samples: 2

batch_size: 16 #512
n_workers: 15
iter: 800000 # 500000
g_lr: 2e-4
d_lr: 4e-4
step_size: 1000
gamma: 0.95
# gamma: 0.1
overwrite: False
# adam_betas: [0.0, 0.9]
adam_betas: [0.5, 0.999]

cv_n_unis: 20 # 30
cv_n_fonts: 9 # 10

print_freq: 10
val_freq: 200
save_freq: 200
tb_freq: 2000